### ISSUE TITLE
Support plugins with bundled binaries?

### ISSUE THREAD

**Issue by bomberstudios** [abynim/sketch-notarizing-assistant#2]
Not sure if I'm doing something wrong, but I'm trying to notarize a plugin with binaries in the Resources folder (Sketch Image Compressor), and it does not show up on the dropdown:

![Screenshot 2019-10-24 at 11 39 46](https://user-images.githubusercontent.com/3832/67473452-fcc48700-f652-11e9-972a-d6762a42002d.png)

Any ideas?

**Comment by abynim** [comment]
Aah looks like your plugin contains individual binaries rather than frameworks or bundles. This is not something I had considered, so thanks for the example! 

I'll update the logic here to look for all binaries, and not just frameworks or bundles.

**Comment by abynim** [comment]
Let me know if the `0.3` update fixes it

**Comment by bomberstudios** [comment]
Works like a charm, thank you so much! 🙌🏻
